const MONETAG_ZONE_ID = '11627577';
const MONETAG_CONTEXT = 'daily_checkin';
const MONETAG_VERIFICATION_CONTEXT = 'verification';
const MONETAG_TASK_CONTEXT = 'task';
const MONETAG_GAMING_CONTEXT = 'gaming';

module.exports = { MONETAG_ZONE_ID, MONETAG_CONTEXT, MONETAG_VERIFICATION_CONTEXT, MONETAG_TASK_CONTEXT, MONETAG_GAMING_CONTEXT };
