  assert(gaming.includes('data-spin-result'));
  assert(gaming.includes('DzMoneyGamingAd'));
  assert(gaming.includes('No advertisement provider is configured'));
  assert(gaming.includes('adapter?.ready'));
  assert(gaming.includes("if (result === 'extra_spin') return '+1 SPIN'"));
  assert(gaming.includes("if (result === 'extra_axe') return '+1 AXE'"));
  assert(gaming.includes('360 * 3 - index * segment'));
  assert(gaming.includes("const wheelResults = ['coin_100'"));
  assert(gaming.includes('renderRewardLists'));
  assert(gaming.includes('gaming-runtime.css'));
  assert(gaming.includes('assetVersion'));
  assert(gaming.includes("const response = await api('/api/gaming/ads/start'"));
  assert(gaming.includes("await adapter.handler({ requestVar: 'gaming', adEventId: response.adEventId })"));
  assert(!gaming.includes('const startPromise = api'));
  assert(!gaming.includes('const adPromise = adapter.handler'));
  assert(!gaming.includes('Promise.all([startPromise, adPromise])'));
  assert(!gaming.includes('setTimeout(resolve, 1500)'));
  assert(css.includes('conic-gradient'));
  assert(css.includes('45deg'));
  assert(css.includes('@container'));
  assert(css.includes(':has('));
